services:
  backend:
    build: .
    container_name: app_medicamentos
    volumes:
      - ./src:/app/src
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3006
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password 
      DATABASE_DATABASE: app_medicamentos
      JWT_SECRET: secret

  database: 
    container_name: app_mdicamentos_db
    image: mysql:8.0.32
    ports:
      - 3306:3306
    
  