services:
  backend: 
    build: .
    container_name: app_medicamentos
    command: npm run dev
    volumes:
      - ./src:/app/src
    depends_on:
      - database:
        condition: service_healthy
    ports:
      -3001:3001
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3006
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password 
      DATABASE_DATABASE: app_medicamentos
      JWT_SECRET: secret

  database: 
    container_name: app_mdicamentos_db
    image: mysql:8.0.32
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      -3306:3306
    
  